# Generated by Django 3.2.4 on 2021-07-21 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0007_heartbeat_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartbeat',
            old_name='member',
            new_name='creator',
        ),
    ]
